import { Question, QuestionKey, Quiz } from './types';

export const seedQuestions: Question[] = [
  {
    id: 'q1',
    stem: 'বাংলা সাহিত্যের প্রাচীনতম নিদর্শন "চর্যাপদ" প্রধানত কোন ছন্দে রচিত?',
    type: 'mcq_single',
    subject: 'বাংলা ভাষা ও সাহিত্য',
    topic: 'প্রাচীন যুগ',
    difficulty: 'medium',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_1_a', text: 'অক্ষরবৃত্ত ছন্দ' },
      { id: 'opt_1_b', text: 'মাত্রাবৃত্ত ছন্দ (পাদাকুলক)' },
      { id: 'opt_1_c', text: 'স্বরবৃত্ত ছন্দ' },
      { id: 'opt_1_d', text: 'অমিত্রাক্ষর ছন্দ' },
    ],
  },
  {
    id: 'q2',
    stem: 'বাংলাদেশের সংবিধানের কোন ভাগে "মৌলিক অধিকার" (Fundamental Rights) সন্নিবেশিত রয়েছে?',
    type: 'mcq_single',
    subject: 'বাংলাদেশ বিষয়াবলী',
    topic: 'সংবিধান ও প্রশাসন',
    difficulty: 'easy',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_2_a', text: 'দ্বিতীয় ভাগ (অনুচ্ছেদ ৮-২৫)' },
      { id: 'opt_2_b', text: 'তৃতীয় ভাগ (অনুচ্ছেদ ২৬-৪৭ক)' },
      { id: 'opt_2_c', text: 'চতুর্থ ভাগ (অনুচ্ছেদ ৪৮-৬৪)' },
      { id: 'opt_2_d', text: 'পঞ্চম ভাগ (অনুচ্ছেদ ৬৫-৯৩)' },
    ],
  },
  {
    id: 'q3',
    stem: 'যদি $x + \\frac{1}{x} = 3$ হয়, তবে $x^3 + \\frac{1}{x^3}$-এর সাংখ্যিক মান কত?',
    type: 'mcq_single',
    subject: 'গাণিতিক যুক্তি',
    topic: 'বীজগণিতীয় সূত্রাবলী',
    difficulty: 'medium',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_3_a', text: '$18$' },
      { id: 'opt_3_b', text: '$27$' },
      { id: 'opt_3_c', text: '$24$' },
      { id: 'opt_3_d', text: '$36$' },
    ],
  },
  {
    id: 'q4',
    stem: 'একটি সমবাহু ত্রিভুজের বাহুর দৈর্ঘ্য $a = 6\\text{ cm}$ হলে, এর ক্ষেত্রফল কত বর্গ সেমি? (যেখানে ক্ষেত্রফল $A = \\frac{\\sqrt{3}}{4}a^2$)',
    type: 'mcq_single',
    subject: 'গাণিতিক যুক্তি',
    topic: 'জ্যামিতি ও পরিমিতি',
    difficulty: 'medium',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_4_a', text: '$9\\sqrt{3}\\text{ cm}^2$' },
      { id: 'opt_4_b', text: '$18\\sqrt{3}\\text{ cm}^2$' },
      { id: 'opt_4_c', text: '$12\\sqrt{3}\\text{ cm}^2$' },
      { id: 'opt_4_d', text: '$36\\sqrt{3}\\text{ cm}^2$' },
    ],
  },
  {
    id: 'q5',
    stem: '$2\\text{ kg}$ ভরের একটি বস্তুকে ভূ-পৃষ্ঠ হতে $10\\text{ m/s}$ বেগে খাড়া উপরের দিকে নিক্ষেপ করা হলে, সর্বোচ্চ উচ্চতায় এর বিভব শক্তি ($E_p$) কত জুল হবে? ($g = 9.8\\text{ ms}^{-2}$ বিবেচনা করুন)',
    type: 'mcq_single',
    subject: 'পদার্থবিজ্ঞান',
    topic: 'কাজ, ক্ষমতা ও শক্তি',
    difficulty: 'hard',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_5_a', text: '$100\\text{ J}$' },
      { id: 'opt_5_b', text: '$98\\text{ J}$' },
      { id: 'opt_5_c', text: '$196\\text{ J}$' },
      { id: 'opt_5_d', text: '$50\\text{ J}$' },
    ],
  },
  {
    id: 'q6',
    stem: 'কার্বনের তেজস্ক্রিয় আইসোটোপ $^{14}_{6}\\text{C}$-এর নিউক্লিয়াসে নিউট্রন সংখ্যা কত?',
    type: 'mcq_single',
    subject: 'রসায়ন',
    topic: 'পরমাণুর গঠন',
    difficulty: 'easy',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_6_a', text: '$6$' },
      { id: 'opt_6_b', text: '$8$' },
      { id: 'opt_6_c', text: '$14$' },
      { id: 'opt_6_d', text: '$20$' },
    ],
  },
  {
    id: 'q7',
    stem: '১৯৭১ সালের মুক্তিযুদ্ধ চলাকালীন ঐতিহাসিক "মুজিবনগর সরকার" কোন তারিখে শপথ গ্রহণ করে?',
    type: 'mcq_single',
    subject: 'বাংলাদেশ বিষয়াবলী',
    topic: 'মুক্তিযুদ্ধ ও স্বাধীনতা',
    difficulty: 'easy',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_7_a', text: '১০ এপ্রিল ১৯৭১' },
      { id: 'opt_7_b', text: '১৭ এপ্রিল ১৯৭১' },
      { id: 'opt_7_c', text: '২৫ মার্চ ১৯৭১' },
      { id: 'opt_7_d', text: '২৬ মার্চ ১৯৭১' },
    ],
  },
  {
    id: 'q8',
    stem: 'Identify the correct passive voice: "Who wrote Hamlet?"',
    type: 'mcq_single',
    subject: 'ইংরেজি ভাষা ও সাহিত্য',
    topic: 'Voice Change',
    difficulty: 'medium',
    defaultMarks: 1,
    language: 'en',
    options: [
      { id: 'opt_8_a', text: 'By whom was Hamlet written?' },
      { id: 'opt_8_b', text: 'Who was written Hamlet by?' },
      { id: 'opt_8_c', text: 'By whom Hamlet was written?' },
      { id: 'opt_8_d', text: 'Who had written Hamlet?' },
    ],
  },
  {
    id: 'q9',
    stem: 'একটি গুণোত্তর ধারার প্রথম পদ $a = 2$ এবং সাধারণ অনুপাত $r = 3$ হলে, প্রথম ৪টি পদের সমষ্টি $S_4 = \\frac{a(r^n - 1)}{r - 1}$ কত হবে?',
    type: 'mcq_single',
    subject: 'গাণিতিক যুক্তি',
    topic: 'সমান্তর ও গুণোত্তর ধারা',
    difficulty: 'hard',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_9_a', text: '$80$' },
      { id: 'opt_9_b', text: '$40$' },
      { id: 'opt_9_c', text: '$120$' },
      { id: 'opt_9_d', text: '$162$' },
    ],
  },
  {
    id: 'q10',
    stem: 'বাইনারি সংখ্যা $(1101)_2$-এর দশমিক (Decimal) মান কোনটি?',
    type: 'mcq_single',
    subject: 'তথ্য ও যোগাযোগ প্রযুক্তি',
    topic: 'সংখ্যা পদ্ধতি',
    difficulty: 'easy',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_10_a', text: '$11$' },
      { id: 'opt_10_b', text: '$13$' },
      { id: 'opt_10_c', text: '$15$' },
      { id: 'opt_10_d', text: '$9$' },
    ],
  },
  {
    id: 'q11',
    stem: 'সৈয়দ ওয়ালীউল্লাহর কালজয়ী "লালসালু" উপন্যাসের কেন্দ্রীয় চরিত্র মজিদ মূলত কোন শ্রেণীর প্রতীক?',
    type: 'mcq_single',
    subject: 'বাংলা ভাষা ও সাহিত্য',
    topic: 'আধুনিক যুগ',
    difficulty: 'medium',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_11_a', text: 'ধর্মীয় গোঁড়ামি ও কুসংস্কারজীবী সুবিধাবাদী সমাজপতি' },
      { id: 'opt_11_b', text: 'নিপীড়িত ভূমিহীন সংগ্রামী কৃষক' },
      { id: 'opt_11_c', text: 'আধুনিক মানবতাবাদী চিন্তাবিদ' },
      { id: 'opt_11_d', text: 'ব্রিটিশ ঔপনিবেশিক শাসক' },
    ],
  },
  {
    id: 'q12',
    stem: 'পদার্থবিজ্ঞানে "পরম শূন্য তাপমাত্রা" (Absolute Zero Temperature) সেলসিয়াস স্কেলে কত ডিগ্রি?',
    type: 'mcq_single',
    subject: 'পদার্থবিজ্ঞান',
    topic: 'তাপ ও তাপগতিবিদ্যা',
    difficulty: 'easy',
    defaultMarks: 1,
    language: 'bn',
    options: [
      { id: 'opt_12_a', text: '$-273.15^\\circ\\text{C}$' },
      { id: 'opt_12_b', text: '$0^\\circ\\text{C}$' },
      { id: 'opt_12_c', text: '$-100^\\circ\\text{C}$' },
      { id: 'opt_12_d', text: '$-459.67^\\circ\\text{C}$' },
    ],
  },
];

export const seedQuestionKeys: Record<string, QuestionKey> = {
  q1: {
    questionId: 'q1',
    correctOptionIds: ['opt_1_b'],
    explanation:
      'চর্যাপদের পদগুলো প্রধানত মাত্রাবৃত্ত ছন্দের ১৬ মাত্রার "পাদাকুলক" রীতিতে রচিত। ড. সুনীতিকুমার চট্টোপাধ্যায় এবং ড. প্রবোধচন্দ্র বাগচী তাঁদের গবেষণায় এটি নিশ্চিত করেছেন।',
  },
  q2: {
    questionId: 'q2',
    correctOptionIds: ['opt_2_b'],
    explanation:
      'বাংলাদেশ সংবিধানের তৃতীয় ভাগে (অনুচ্ছেদ ২৬ থেকে ৪৭ক) মৌলিক অধিকারসমূহ বিশদভাবে লিপিবদ্ধ রয়েছে। অনুচ্ছেদ ৪৪ অনুযায়ী মৌলিক অধিকার বলবৎকরণের জন্য সুপ্রিম কোর্টে আবেদন করা যায়।',
  },
  q3: {
    questionId: 'q3',
    correctOptionIds: ['opt_3_a'],
    explanation:
      'বীজগণিতীয় অনুসিদ্ধান্ত অনুযায়ী:\n$$x^3 + \\frac{1}{x^3} = \\left(x + \\frac{1}{x}\\right)^3 - 3 \\cdot x \\cdot \\frac{1}{x} \\cdot \\left(x + \\frac{1}{x}\\right)$$\nমান বসিয়ে পাই: $3^3 - 3(3) = 27 - 9 = 18$। অতএব সঠিক উত্তর ১৮।',
  },
  q4: {
    questionId: 'q4',
    correctOptionIds: ['opt_4_a'],
    explanation:
      'সমবাহু ত্রিভুজের ক্ষেত্রফল:\n$$A = \\frac{\\sqrt{3}}{4}a^2 = \\frac{\\sqrt{3}}{4} \\times 6^2 = \\frac{\\sqrt{3}}{4} \\times 36 = 9\\sqrt{3}\\text{ cm}^2$$',
  },
  q5: {
    questionId: 'q5',
    correctOptionIds: ['opt_5_a'],
    explanation:
      'শক্তির নিত্যতা সূত্র অনুসারে, নিক্ষেপের মুহূর্তে গতিশক্তি $E_k = \\frac{1}{2}mv^2$ সর্বোচ্চ বিন্দুতে সম্পূর্ণরূপে বিভব শক্তিতে ($E_p$) রূপান্তরিত হয়।\n$$E_p = \\frac{1}{2} \\times 2\\text{ kg} \\times (10\\text{ m/s})^2 = 100\\text{ J}$$',
  },
  q6: {
    questionId: 'q6',
    correctOptionIds: ['opt_6_b'],
    explanation:
      'ভরসংখ্যা $A = 14$ এবং পারমাণবিক সংখ্যা (প্রোটন) $Z = 6$। সুতরাং নিউট্রন সংখ্যা $N = A - Z = 14 - 6 = 8$।',
  },
  q7: {
    questionId: 'q7',
    correctOptionIds: ['opt_7_b'],
    explanation:
      '১০ এপ্রিল ১৯৭১ সালে মুজিবনগর সরকার গঠিত হয় এবং ১৭ এপ্রিল মেহেরপুরের বৈদ্যনাথতলার (বর্তমান মুজিবনগর) আম্রকাননে আনুষ্ঠানিকভাবে শপথ গ্রহণ করে।',
  },
  q8: {
    questionId: 'q8',
    correctOptionIds: ['opt_8_a'],
    explanation:
      'Interrogative sentence with "Who" changes into "By whom + auxiliary verb (was) + subject (Hamlet) + past participle (written)?". Correct structure is: "By whom was Hamlet written?".',
  },
  q9: {
    questionId: 'q9',
    correctOptionIds: ['opt_9_a'],
    explanation:
      'যেহেতু $r = 3 > 1$, সমষ্টির সূত্র:\n$$S_4 = \\frac{a(r^4 - 1)}{r - 1} = \\frac{2(3^4 - 1)}{3 - 1} = \\frac{2(81 - 1)}{2} = 80$$',
  },
  q10: {
    questionId: 'q10',
    correctOptionIds: ['opt_10_b'],
    explanation:
      'বাইনারি রূপান্তর:\n$$(1101)_2 = (1 \\times 2^3) + (1 \\times 2^2) + (0 \\times 2^1) + (1 \\times 2^0) = 8 + 4 + 0 + 1 = 13$$',
  },
  q11: {
    questionId: 'q11',
    correctOptionIds: ['opt_11_a'],
    explanation:
      'উপন্যাসিক সৈয়দ ওয়ালীউল্লাহ মজিদ চরিত্রের মাধ্যমে সাধারণ ধর্মভীরু গ্রামীণ মানুষের অন্ধবিশ্বাস ও কুসংস্কারকে পুঁজি করে কীভাবে স্বার্থপর সমাজপতিরা নিজেদের কর্তৃত্ব কায়েম করে তা বাস্তবসম্মতভাবে ফুটিয়ে তুলেছেন।',
  },
  q12: {
    questionId: 'q12',
    correctOptionIds: ['opt_12_a'],
    explanation:
      'কেলভিন স্কেলের $0\\text{ K}$ তাপমাত্রা সেলসিয়াস স্কেলে $-273.15^\\circ\\text{C}$ হিসেবে নির্ধারিত, যেখানে গ্যাসের আণবিক গতি সম্পূর্ণরূপে থেমে যায়।',
  },
};

export const seedQuizzes: Quiz[] = [
  {
    id: 'quiz-bcs-mock-01',
    slug: 'bcs-preli-model-test-01',
    title: '৪৫তম বিসিএস প্রিলিমিনারি পূর্ণাঙ্গ মক টেস্ট - ০১',
    description:
      'বাস্তব বিসিএস প্রিলিমিনারি অনুরূপ সিলেবাসভিত্তিক মক টেস্ট। প্রতিটি ভুলের জন্য ০.২৫ নেগেটিভ মার্কিং এবং নির্দিষ্ট সময়সীমা অন্তর্ভুক্ত।',
    type: 'mock',
    subject: 'বিসিএস প্রিলিমিনারি স্পেশাল',
    difficulty: 'medium',
    totalQuestions: 12,
    status: 'published',
    createdAt: '2026-10-06T06:00:00Z',
    questionIds: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12'],
    settings: {
      durationMinutes: 15,
      totalMarks: 12,
      negativeRatio: 0.25,
      shuffleQuestions: true,
      shuffleOptions: true,
      resultMode: 'after_submit',
      passPercentage: 50,
      maxAttempts: null,
    },
  },
  {
    id: 'quiz-math-special',
    slug: 'math-mental-ability-quiz',
    title: 'গাণিতিক যুক্তি ও মানসিক দক্ষতা প্র্যাকটিস টেস্ট',
    description:
      'KaTeX সমীকরণ ও গাণিতিক সূত্রের নির্ভুল সমাধানের জন্য বিশেষ কুইজ। প্রতিটি উত্তরের সাথে সাথে বিস্তারিত ব্যাখ্যা দেখার সুযোগ রয়েছে।',
    type: 'quiz',
    subject: 'গাণিতিক যুক্তি',
    difficulty: 'hard',
    totalQuestions: 5,
    status: 'published',
    createdAt: '2026-10-06T06:00:00Z',
    questionIds: ['q3', 'q4', 'q9', 'q10', 'q12'],
    settings: {
      durationMinutes: 8,
      totalMarks: 5,
      negativeRatio: 0,
      shuffleQuestions: false,
      shuffleOptions: false,
      resultMode: 'immediate',
      passPercentage: 60,
      maxAttempts: null,
    },
  },
  {
    id: 'quiz-bangla-literature',
    slug: 'bangla-bhasha-sahitya-speed-quiz',
    title: 'বাংলা ভাষা ও সাহিত্যের সেরা প্রস্তুতি কুইজ',
    description:
      'প্রাচীন ও মধ্যযুগীয় সাহিত্যের কালজয়ী প্রশ্নমালা। দ্রুত রিভিশন ও আত্মবিশ্বাস যাচাইয়ের চমৎকার সুযোগ।',
    type: 'quiz',
    subject: 'বাংলা ভাষা ও সাহিত্য',
    difficulty: 'easy',
    totalQuestions: 4,
    status: 'published',
    createdAt: '2026-10-06T06:00:00Z',
    questionIds: ['q1', 'q11', 'q7', 'q2'],
    settings: {
      durationMinutes: 5,
      totalMarks: 4,
      negativeRatio: 0.25,
      shuffleQuestions: false,
      shuffleOptions: false,
      resultMode: 'after_submit',
      passPercentage: 50,
      maxAttempts: null,
    },
  },
  {
    id: 'quiz-science-admission',
    slug: 'science-admission-mock',
    title: 'বিশ্ববিদ্যালয় "ক" ইউনিট বিজ্ঞান ভর্তি মক টেস্ট',
    description:
      'এইচএসসি পদার্থবিজ্ঞান ও রসায়নের মূল ধারণাসমূহ নিয়ে দ্রুতগতির প্রস্তুতি পরীক্ষা। বাস্তব ভর্তি পরীক্ষার অনুরূপ সময় ব্যবস্থাপনা।',
    type: 'mock',
    subject: 'বিজ্ঞান ও প্রযুক্তি',
    difficulty: 'hard',
    totalQuestions: 4,
    status: 'published',
    createdAt: '2026-10-06T06:00:00Z',
    questionIds: ['q5', 'q6', 'q12', 'q3'],
    settings: {
      durationMinutes: 6,
      totalMarks: 4,
      negativeRatio: 0.25,
      shuffleQuestions: true,
      shuffleOptions: true,
      resultMode: 'after_submit',
      passPercentage: 60,
      maxAttempts: null,
    },
  },
];
